name: Documentation

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - uses: mattnotmitt/doxygen-action@edge
        name: Generate documentation

      - name: setup-pages
        uses: actions/configure-pages@v4
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/generated/html'
      - name: deploy-github-page
        id: deployment
        uses: actions/deploy-pages@v4